### ISSUE TITLE
2016.05 does not boot on pogo v4

### ISSUE THREAD

**Issue by nwf** [mibodhi/u-boot-kirkwood#5]
I checked out and built 394caefb36f7e883b73565a2d9347fc47e72903b and then attempted to kwboot it using `kwboot -b kwb -p -B 115200 -t /dev/ttyUSB0` and while the image transferred successfully, the machine never appeared to do anything; there was no output on the serial console and the LEDs stayed off.

Thank you for looking at this again.  What more can I do to provide useful information?  Would you like me to ship you a pogo4 board?

Cheers,
--nwf;

**Comment by mibodhi** [comment]
Hi Nathan,

I did test a built from GitHub source for a final check. Have you tried an identical Git clone on the latest branch (instead of checking out using the commit hash)?

-bodhi

**Comment by mibodhi** [comment]
On second thought, check your serial port, it might be faulty.

**Comment by nwf** [comment]
Oh FFS, I finally got a chance to look at this again and boy do I have egg on my face.  Nevermind, I wasn't properly paying attention and wasn't writing the entire bootloader to flash.  Sorry for noise.
