### ISSUE TITLE
Compile prolem with NSAxxx

### ISSUE THREAD

**Issue by berte** [mibodhi/u-boot-kirkwood#8]
Hi all,

I could not compile Zyxel NSA boards and I'm getting error cfgchk phase likewise as below;

  LD      u-boot
  OBJCOPY u-boot.srec
  OBJCOPY u-boot-nodtb.bin
  SYM     u-boot.sym
  COPY    u-boot.bin
  CFGCHK  u-boot.cfg
Error: You must add new CONFIG options using Kconfig
The following new ad-hoc CONFIG options were detected:
CONFIG_CMD_ENV
CONFIG_MACH_NSA325
CONFIG_SYS_HUSH_PARSER
CONFIG_SYS_NO_FLASH

Please add these via Kconfig instead. Find a suitable Kconfig
file and add a 'config' or 'menuconfig' option.
Makefile:862: recipe for target 'all' failed
make: *** [all] Error 1

Any idea/suggestion would be great!

Thanks

**Comment by mibodhi** [comment]
berte,

Did you set the tags to https://github.com/mibodhi/u-boot-kirkwood/tree/v2017.07-kirkwood-tld-1
or use branch 2017.07-kirkwood-tld-1?

And did you run this command to compile:
`make nsa325_config
`

-bodhi

**Comment by berte** [comment]
Hi mibodhi,

I'm using 2017.07-kirkwood-tld-1 branch and also I tried `make nsa325_config`

**Comment by mibodhi** [comment]
berte,

Did you clone  the Git or download a zip file?  I've verified this build on my Git. I couldn't see why you would have this problem.

-bodhi
